name: Generate a snapshot in MVNCentral
on: 
  push:
    branches:    
      - 'feature/checkGitAction'
jobs:  
  Generate-a-snapshot-in-MVNCentral:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository code
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up settigs.xml
        uses: s4u/maven-settings-action@v2.4.1
        with:
          sonatypeSnapshots: true
          servers: |
            [{ "id": "ossrh", "username": ${{ secrets.MAVEN_USERNAME }}, "password": ${{ secrets.MAVEN_CENTRAL_TOKEN }}, "privateKey": ${{ secrets.MAVEN_GPG_PASSPHRASE }}, "passphrase": ${{ secrets.MAVEN_GPG_PASSPHRASE }} }]
      - name: Check files
        run: |
          mvn -v
          java -version
          cat $HOME/.m2/settings.xml
      - name: Publish to Apache Maven Central
        run: mvn -U -X clean deploy -Pgenerate-version
