name: Send mail
on:
  workflow_dispatch :
    inputs:
      MAIL_DESTINY:
        description: Mail destiny
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Imatia
      BRANCH:
        description: 'Branch'
        type: choice
        required: true
        default: 'feature/update-mail'
        options:
          - main
          - develop
          - feature/update-mail
jobs:
  Send-mail:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get input parameters
        run: |
          echo "BRANCH=${{ github.event.inputs.BRANCH }}" >> $GITHUB_ENV
          DESTINY=${{ github.event.inputs.MAIL_DESTINY }}
          RECIPIENT=${{secrets.EMAIL_TARGET_TEST}}
          if [ "$DESTINY" = "Imatia" ]; then
          RECIPIENT=${{secrets.EMAIL_TARGET}}
          fi
          echo "RECIPIENT=$RECIPIENT" >> $GITHUB_ENV
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0
      - name: Setup Java JDK and Maven
        uses: ontimize/setup-java-maven-gitAction@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Getting version
        run: |
          version=$(mvn help:evaluate -q -Dexpression=project.version -DforceStdout)
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Nueva versión de Ontimize EE 🚀
          to: ${{ env.RECIPIENT }}
          from: ${{secrets.EMAIL_USER_FROM}}
          html_body: file://mail_to_send.html
          convert_markdown: true